# Generated by Django 4.2.7 on 2023-11-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('artist', models.CharField(max_length=250, verbose_name='artist')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album_covers', verbose_name='cover')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
            },
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'service review', 'verbose_name_plural': 'service reviews'},
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='doctor',
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to='clinic.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='content',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='content'),
        ),
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=4000, null=True, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.album', verbose_name='album')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'album review',
                'verbose_name_plural': 'album reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
