# Generated by Django 4.2.7 on 2023-11-13 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_album_alter_servicereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
    ]
