# Generated by Django 4.2.7 on 2023-11-14 11:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_albumreview_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServiceOrder',
            fields=[
                ('serviceorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinic.serviceorder')),
                ('custom_text', tinymce.models.HTMLField(blank=True, default='', max_length=500, verbose_name='custom_text')),
                ('custom_img', models.ImageField(blank=True, null=True, upload_to='custom_img', verbose_name='custom_img')),
            ],
            options={
                'verbose_name': 'custom service order',
                'verbose_name_plural': 'custom service orders',
            },
            bases=('clinic.serviceorder',),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews', to='clinic.album', verbose_name='album'),
        ),
    ]
