# Generated by Django 4.2.7 on 2023-11-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_customserviceorder_alter_albumreview_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={},
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='service'),
        ),
    ]
