# Generated by Django 4.2.7 on 2023-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(blank=True, default='', max_length=500, verbose_name='custom_text')),
                ('custom_img', models.ImageField(blank=True, null=True, upload_to='custom_img', verbose_name='custom_img')),
            ],
            options={
                'verbose_name': 'custom service',
                'verbose_name_plural': 'custom services',
            },
        ),
        migrations.CreateModel(
            name='RegularService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('about', models.TextField(blank=True, default='', max_length=10000, verbose_name='about')),
            ],
            options={
                'verbose_name': 'regular service',
                'verbose_name_plural': 'regular services',
            },
        ),
    ]
