# Generated by Django 4.2.7 on 2023-11-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_customservice_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.instrument', verbose_name='instrument'),
        ),
    ]
