# Generated by Django 4.2.7 on 2023-11-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_serviceorder_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clinic.doctor', verbose_name='doctor'),
        ),
    ]
