# Generated by Django 4.2.7 on 2023-11-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0012_serviceorder_custom_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Confirmed'), (1, 'Completed'), (2, 'Cancelled')], default=0, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.album', verbose_name='album')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_sales', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
    ]
